show pyplint score

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -18,22 +18,38 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.12'
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pylint  # Install pylint
-          pip install -r requirements.txt  # Install your project dependencies
-
-      - name: Run pylint
-        run: |
-          pylint src/purchase_predict/**/*.py > pylint_report.txt || true
-        continue-on-error: true
-      - name: Display report
-        run: |
-          cat pylint_report.txt
+      - name: Pylint batch
+        uses: Silleellie/pylint-github-action@v2
+        with: 
+          lint-path: src/purchase_predict/**/*.py
+          python-version: 3.12
+          requirements-path: requirements.txt
+          readme-path: README.md
+          badge-text: PyLint Score
+          color-bad-score: red
+          color-ok-score: orange
+          color-good-score: yellow
+          color-perfect-score: brightgreen
 
       - name: Display pylint score
         run: |
-          score=$(grep -oP '(?<=rated at )\d+\.\d+' pylint_report.txt || echo "Score not found")
-          echo "Pylint score: $score/10"
+          echo "Pylint report:"
+          echo "${{ steps.pylint.outputs.pylint_report }}"
+      # - name: Install dependencies
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install pylint  # Install pylint
+      #     pip install -r requirements.txt  # Install your project dependencies
+
+      # - name: Run pylint
+      #   run: |
+      #     pylint src/purchase_predict/**/*.py > pylint_report.txt || true
+      #   continue-on-error: true
+      # - name: Display report
+      #   run: |
+      #     cat pylint_report.txt
+
+      # - name: Display pylint score
+      #   run: |
+      #     score=$(grep -oP '(?<=rated at )\d+\.\d+' pylint_report.txt || echo "Score not found")
+      #     echo "Pylint score: $score/10"
